init:
  detector: COCOA

  gpu: 0
  precision: medium
  chunk_size: 512 # 128
  batch_size: 512 # 256
  num_workers: 9

  model:

    # 200k (mod_e_th = 0) //All these paths come from stage 2 training (aka s2 traiinign directory not s1 as in the last config) 
    config_path_v   : /srv01/agrp/annai/annai/QURK-GLUON/samples_produce/Cocoa/HGPFLOW_v2/experiments/hgpflow_v2/cocoapythia500gevxs2xxx9a56ipcxj/config_v.yml
    config_path_ms1 : /srv01/agrp/annai/annai/QURK-GLUON/samples_produce/Cocoa/HGPFLOW_v2/experiments/hgpflow_v2/cocoapythia500gevxs2xxx9a56ipcxj/config_ms1.yml
    config_path_ms2 : /srv01/agrp/annai/annai/QURK-GLUON/samples_produce/Cocoa/HGPFLOW_v2/experiments/hgpflow_v2/cocoapythia500gevxs2xxx9a56ipcxj/config_ms2.yml
    checkpoint_path : /srv01/agrp/annai/annai/QURK-GLUON/samples_produce/Cocoa/HGPFLOW_v2/experiments/hgpflow_v2/cocoapythia500gevxs2xxx9a56ipcxj/checkpoints/epoch=19-val_total_loss=0.0696.ckpt


  ind_threshold_loose: 0.2
  ind_threshold_plot: 0.48
  store_seg: false

items:
 
  - info: "Zqg"
    run_pred: true
    run_plot: false

    seg_path: /storage/agrp/nilotpal/HGPFlow_v2/data/cocoa/Ntuples_ttbar_noID_withSmearing_newpflow_17122023/merged_skim_seg_bw0.4.root
    truth_path: null
    pred_path: null

    dir_flag: Ntuples_ttbar_noID_withSmearing_newpflow_17122023
    n_events: -1

#
#  - info: "ZHbb pTHatMin400"
#    run_pred: true
#    run_plot: false
#
#    seg_path: /storage/agrp/nilotpal/HGPFlow_v2/data/cocoa/Ntuples_ZHbb_pTHatMin400_noID_withSmearing_newpflow_17122023/merged_skim_seg_bw0.4.root
#    truth_path: null
#    pred_path: null
#
#    dir_flag: Ntuples_ZHbb_pTHatMin400_noID_withSmearing_newpflow_17122023
#    n_events: -1
#
#
#  - info: "ZHbb pTHatMin100"
#    run_pred: true
#    run_plot: false
#
#    seg_path: /storage/agrp/nilotpal/HGPFlow_v2/data/cocoa/Ntuples_ZHbb_pTHatMin100_noID_withSmearing_newpflow_20112023/merged_skim_seg_bw0.4.root
#    truth_path: null
#    pred_path: null
#
#    dir_flag: Ntuples_ZHbb_pTHatMin100_noID_withSmearing_newpflow_20112023
#    n_events: -1
#
#
#  - info: "single pions inclusive"
#    run_pred: true
#    run_plot: false
#
#    seg_path: /storage/agrp/nilotpal/HGPFlow_v2/data/cocoa/Ntuples_charged_pion_noID_withSmearing_newpflow_optData_20122023/test_skim_seg_bw0.4.root
#    truth_path: null
#    pred_path: null
#
#    dir_flag: Ntuples_charged_pion_noID_withSmearing_newpflow_optData_20122023
#    n_events: -1
#
#
#  - info: "single pions bin 0"
#    run_pred: true
#    run_plot: false
#
#    seg_path: /storage/agrp/nilotpal/HGPFlow_v2/data/cocoa/Ntuples_charged_pion_noID_withSmearing_newpflow_29092024/merged_bin_0_allEta_skim_seg_bw0.4.root
#    truth_path: null
#    pred_path: null
#
#    dir_flag: Ntuples_charged_pion_noID_withSmearing_newpflow_29092024
#    n_events: -1
#
#
#  - info: "single pions bin 1"
#    run_pred: true
#    run_plot: false
#
#    seg_path: /storage/agrp/nilotpal/HGPFlow_v2/data/cocoa/Ntuples_charged_pion_noID_withSmearing_newpflow_29092024/merged_bin_1_allEta_skim_seg_bw0.4.root
#    truth_path: null
#    pred_path: null
#
#    dir_flag: Ntuples_charged_pion_noID_withSmearing_newpflow_29092024
#    n_events: -1
#
#
#  - info: "single pions bin 2"
#    run_pred: true
#    run_plot: false
#
#    seg_path: /storage/agrp/nilotpal/HGPFlow_v2/data/cocoa/Ntuples_charged_pion_noID_withSmearing_newpflow_29092024/merged_bin_2_allEta_skim_seg_bw0.4.root
#    truth_path: null
#    pred_path: null
#
#    dir_flag: Ntuples_charged_pion_noID_withSmearing_newpflow_29092024
#    n_events: -1
#
#
#  - info: "single pions bin 3"
#    run_pred: true
#    run_plot: false
#
#    seg_path: /storage/agrp/nilotpal/HGPFlow_v2/data/cocoa/Ntuples_charged_pion_noID_withSmearing_newpflow_29092024/merged_bin_3_allEta_skim_seg_bw0.4.root
#    truth_path: null
#    pred_path: null
#
#    dir_flag: Ntuples_charged_pion_noID_withSmearing_newpflow_29092024
#    n_events: -1
#
#
#  - info: "single pions bin 4"
#    run_pred: true
#    run_plot: false
#
#    seg_path: /storage/agrp/nilotpal/HGPFlow_v2/data/cocoa/Ntuples_charged_pion_noID_withSmearing_newpflow_29092024/merged_bin_4_allEta_skim_seg_bw0.4.root
#    truth_path: null
#    pred_path: null
#
#    dir_flag: Ntuples_charged_pion_noID_withSmearing_newpflow_29092024
#    n_events: -1
#
#
#  - info: "single pions bin 5"
#    run_pred: true
#    run_plot: false
#
#    seg_path: /storage/agrp/nilotpal/HGPFlow_v2/data/cocoa/Ntuples_charged_pion_noID_withSmearing_newpflow_29092024/merged_bin_5_allEta_skim_seg_bw0.4.root
#    truth_path: null
#    pred_path: null
#
#    dir_flag: Ntuples_charged_pion_noID_withSmearing_newpflow_29092024
#    n_events: -1
