project_name: hgpflow_v2
run_name: cv2xv2xs1

device: cuda
num_devices: 1

train_components: [hg_model] # hg_model | hyperedge | [hg_model, hyperedge]

resume_from_checkpoint: null

num_epochs: 150
eval_every_n_epoch: 1

batchsize_train: 32
batchsize_val: 64
n_cells_threshold_sampler: 4500 # 1700

path_train: /storage/agrp/dreyet/PFlow/samples/dijet/Ntuples_dijet_noID_withSmearing_newpflow_15122023/train_skim_seg_bw0.4.root
path_val  : /storage/agrp/dreyet/PFlow/samples/dijet/Ntuples_dijet_noID_withSmearing_newpflow_15122023/val_skim_seg_bw0.4.root

reduce_ds_train: -1
reduce_ds_val: -1

num_workers: 3 # 5
n_ray: 0

learning_rate: 3.0e-6
# lr_scheduler:
#     name: CustomLRScheduler
#     warm_start_epochs: 0.05
#     cosine_epochs: 0.8
#     eta_min: 5.0e-5
#     last_epoch: -1

base_root_dir: /storage/agrp/nilotpal/HGPFlow_v2/experiments

ind_loss_wt: 1.0
inc_loss_wt: 1.0
track_fix_wt: 1.e+5

train_log_every_n_steps: 10
n_event_displays: 5
event_idxs_to_display: [0, 1, 29, 51, 52] # overwrites n_event_displays

# things I am testing...
do_consistent_match: true # true | false (paper)
loss_discount_factor: "torch.ones(12)" # "torch.linspace(1.0, 0.2, num=16)" | "torch.ones(16)"  
random_bptt: false # true | false (false is from the paper)

